name: Build & Release Binary

on:
  push:
    tags:
      - 'v20[0-9][0-9]-[0-1][0-9]-[0-3][0-9][a-z]' # v2025-06-07a

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Linux x86 Binary
          path: target/release/nktc

